// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwL2EUAOrTKSD6nnrsoV4wJirZM3gnBg8',
    appId: '1:408149794147:web:c42011dd66d380f7388756',
    messagingSenderId: '408149794147',
    projectId: 'hdims-4be72',
    authDomain: 'hdims-4be72.firebaseapp.com',
    storageBucket: 'hdims-4be72.appspot.com',
    measurementId: 'G-SE6X4QV0C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAss1NQs3rTMKbChH_5xRF3PHyUcSrErkA',
    appId: '1:408149794147:android:a5e7b35d39078c02388756',
    messagingSenderId: '408149794147',
    projectId: 'hdims-4be72',
    storageBucket: 'hdims-4be72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUUN-tRsr2wfkaYskJKvPmK6kvhWoQ9QY',
    appId: '1:408149794147:ios:4797fb4208537b50388756',
    messagingSenderId: '408149794147',
    projectId: 'hdims-4be72',
    storageBucket: 'hdims-4be72.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUUN-tRsr2wfkaYskJKvPmK6kvhWoQ9QY',
    appId: '1:408149794147:ios:4797fb4208537b50388756',
    messagingSenderId: '408149794147',
    projectId: 'hdims-4be72',
    storageBucket: 'hdims-4be72.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwL2EUAOrTKSD6nnrsoV4wJirZM3gnBg8',
    appId: '1:408149794147:web:ab2331c5e219a2e1388756',
    messagingSenderId: '408149794147',
    projectId: 'hdims-4be72',
    authDomain: 'hdims-4be72.firebaseapp.com',
    storageBucket: 'hdims-4be72.appspot.com',
    measurementId: 'G-S3N3DBV378',
  );
}
